secrets:
  redis_password:
    file: ./secrets/redis_password.txt
  mongo_password:
    file: ./secrets/mongo_password.txt
  token:
    file: ./secrets/token.txt

services:
  app:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    secrets:
      - token
      - mongo_password
      - redis_password

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      sh -c "redis-server
      --requirepass \"$$(cat /run/secrets/redis_password)\"
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru"
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    networks:
      - app-network

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    command: [ "mongod", "--quiet" ]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  redis_data:
  mongodb_data:

networks:
  app-network:
    driver: bridge
